name: Build and test the esy package

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Install esy, verdaccio and esy-package
        run: npm install -g @esy-nightly/esy verdaccio esy-package@dev

      - name: Run end-to-end tests on the package 
        run: DEBUG=bale*,verdaccio* esy-package
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: release
          path: package.tar.gz
